/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/problems": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Problems */
    get: operations["list_problems_api_problems_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/problems/{slug}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Problem Detail */
    get: operations["problem_detail_api_problems__slug__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Sessions */
    get: operations["list_sessions_api_sessions_get"];
    put?: never;
    /** Create Session */
    post: operations["create_session_api_sessions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sessions/{session_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Session */
    delete: operations["delete_session_api_sessions__session_id__delete"];
    options?: never;
    head?: never;
    /** Update Session */
    patch: operations["update_session_api_sessions__session_id__patch"];
    trace?: never;
  };
  "/api/sessions/{session_id}/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Session Stats */
    get: operations["session_stats_api_sessions__session_id__stats_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sessions/{session_id}/problems/{slug}/draft": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Save Draft */
    put: operations["save_draft_api_sessions__session_id__problems__slug__draft_put"];
    post?: never;
    /** Reset Draft */
    delete: operations["reset_draft_api_sessions__session_id__problems__slug__draft_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sessions/{session_id}/problems/{slug}/run": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Run */
    post: operations["run_api_sessions__session_id__problems__slug__run_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sessions/{session_id}/problems/{slug}/submit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Submit */
    post: operations["submit_api_sessions__session_id__problems__slug__submit_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sessions/{session_id}/problems/{slug}/submissions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Submissions */
    get: operations["list_submissions_api_sessions__session_id__problems__slug__submissions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sessions/{session_id}/problems/{slug}/chat": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Chat */
    get: operations["get_chat_api_sessions__session_id__problems__slug__chat_get"];
    put?: never;
    /** Send Chat */
    post: operations["send_chat_api_sessions__session_id__problems__slug__chat_post"];
    /** Clear Chat */
    delete: operations["clear_chat_api_sessions__session_id__problems__slug__chat_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sessions/{session_id}/patterns/{slug}/chat": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Pattern Chat */
    get: operations["get_pattern_chat_api_sessions__session_id__patterns__slug__chat_get"];
    put?: never;
    /** Send Pattern Chat */
    post: operations["send_pattern_chat_api_sessions__session_id__patterns__slug__chat_post"];
    /** Clear Pattern Chat */
    delete: operations["clear_pattern_chat_api_sessions__session_id__patterns__slug__chat_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Bucket */
    Bucket: {
      /** Solved */
      solved: number;
      /** Total */
      total: number;
    };
    /** CaseResult */
    CaseResult: {
      /** Args */
      args: string[];
      /** Ok */
      ok?: boolean | null;
      /** Output */
      output?: string | null;
      /** Expected */
      expected?: string | null;
      /** Stdout */
      stdout?: string | null;
      /** Error */
      error?: string | null;
      /** Ms */
      ms?: number | null;
      /** Input Error */
      input_error?: string | null;
    };
    /** ChatHistory */
    ChatHistory: {
      /** Messages */
      messages: components["schemas"]["ChatMessage"][];
    };
    /** ChatIn */
    ChatIn: {
      /** Message */
      message: string;
      /**
       * Code
       * @default
       */
      code: string;
    };
    /** ChatMessage */
    ChatMessage: {
      /**
       * Role
       * @enum {string}
       */
      role: "user" | "assistant";
      /** Content */
      content: string;
    };
    /** ChatReply */
    ChatReply: {
      message: components["schemas"]["ChatMessage"];
    };
    /** CodeIn */
    CodeIn: {
      /** Code */
      code: string;
    };
    /** DifficultyBuckets */
    DifficultyBuckets: {
      Easy: components["schemas"]["Bucket"];
      Medium: components["schemas"]["Bucket"];
      Hard: components["schemas"]["Bucket"];
    };
    /** EditorField */
    EditorField: {
      /** Name */
      name: string;
      /** Type */
      type: string;
    };
    /** Example */
    Example: {
      /** Args */
      args: string[];
      /** Output */
      output: string | null;
      /** Note */
      note?: string | null;
    };
    /** FailingCase */
    FailingCase: {
      /** Args */
      args: string[];
      /** Ok */
      ok?: boolean | null;
      /** Output */
      output?: string | null;
      /** Expected */
      expected?: string | null;
      /** Stdout */
      stdout?: string | null;
      /** Error */
      error?: string | null;
      /** Ms */
      ms?: number | null;
      /** Input Error */
      input_error?: string | null;
      /** Index */
      index: number;
      /** Is Example */
      is_example: boolean;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Health */
    Health: {
      /** Ok */
      ok: boolean;
      seeding: components["schemas"]["SeedState"];
    };
    /** ProblemDetail */
    ProblemDetail: {
      /** Slug */
      slug: string;
      /** Title */
      title: string;
      /**
       * Difficulty
       * @enum {string}
       */
      difficulty: "Easy" | "Medium" | "Hard";
      /** Pattern */
      pattern: string;
      /** Topics */
      topics: string[];
      /** Companies */
      companies: string[];
      /** Status */
      status: ("solved" | "attempted") | null;
      /** Attempts */
      attempts: number;
      /** Statement */
      statement: string;
      /** Constraints */
      constraints: string[];
      /** Hints */
      hints: string[];
      /**
       * Kind
       * @enum {string}
       */
      kind: "function" | "design";
      /** Fields */
      fields: components["schemas"]["EditorField"][];
      /** Examples */
      examples: components["schemas"]["Example"][];
      /** Default Cases */
      default_cases: string[][];
      /** Starter Code */
      starter_code: string;
      /** Draft */
      draft: string | null;
    };
    /** ProblemList */
    ProblemList: {
      /** Patterns */
      patterns: string[];
      /** Problems */
      problems: components["schemas"]["ProblemSummary"][];
    };
    /** ProblemSummary */
    ProblemSummary: {
      /** Slug */
      slug: string;
      /** Title */
      title: string;
      /**
       * Difficulty
       * @enum {string}
       */
      difficulty: "Easy" | "Medium" | "Hard";
      /** Pattern */
      pattern: string;
      /** Topics */
      topics: string[];
      /** Companies */
      companies: string[];
      /** Status */
      status: ("solved" | "attempted") | null;
      /** Attempts */
      attempts: number;
    };
    /** RecentSubmission */
    RecentSubmission: {
      /** Id */
      id: string;
      /** Problem */
      problem: string;
      /** Title */
      title: string;
      /** Verdict */
      verdict: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Runtime Ms */
      runtime_ms: number | null;
    };
    /** RunIn */
    RunIn: {
      /** Code */
      code: string;
      /** Cases */
      cases: unknown[][];
    };
    /** RunResult */
    RunResult: {
      /** Verdict */
      verdict: string;
      /** Compile Error */
      compile_error: string | null;
      /** Cases */
      cases: components["schemas"]["CaseResult"][];
      /** Passed */
      passed: number;
      /** Runtime Ms */
      runtime_ms: number | null;
    };
    /** SeedState */
    SeedState: {
      /** Status */
      status: string;
      /** Done */
      done: number;
      /** Total */
      total: number;
      /** Errors */
      errors: string[];
    };
    /** Session */
    Session: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /**
       * Target
       * @enum {string}
       */
      target: "google" | "meta" | "general";
      /** Notes */
      notes: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Last Active At */
      last_active_at: string | null;
      /** Solved */
      solved: number;
      /** Attempted */
      attempted: number;
    };
    /** SessionIn */
    SessionIn: {
      /** Name */
      name: string;
      /**
       * Target
       * @default general
       * @enum {string}
       */
      target: "google" | "meta" | "general";
      /**
       * Notes
       * @default
       */
      notes: string;
    };
    /** SessionPatch */
    SessionPatch: {
      /** Name */
      name?: string | null;
      /** Target */
      target?: ("google" | "meta" | "general") | null;
      /** Notes */
      notes?: string | null;
    };
    /** SessionStats */
    SessionStats: {
      by_difficulty: components["schemas"]["DifficultyBuckets"];
      /** By Pattern */
      by_pattern: {
        [key: string]: components["schemas"]["Bucket"];
      };
      /** Submissions */
      submissions: number;
      /** Accepted */
      accepted: number;
      /** Recent */
      recent: components["schemas"]["RecentSubmission"][];
    };
    /** Submission */
    Submission: {
      /** Id */
      id: string;
      /** Verdict */
      verdict: string;
      /** Passed */
      passed: number;
      /** Total */
      total: number;
      /** Runtime Ms */
      runtime_ms: number | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Code */
      code: string;
    };
    /** SubmitResult */
    SubmitResult: {
      /** Submission Id */
      submission_id: string;
      /** Verdict */
      verdict: string;
      /** Passed */
      passed: number;
      /** Total */
      total: number;
      /** Compile Error */
      compile_error: string | null;
      /** Runtime Ms */
      runtime_ms: number | null;
      failing: components["schemas"]["FailingCase"] | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  list_problems_api_problems_get: {
    parameters: {
      query?: {
        session_id?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemList"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  problem_detail_api_problems__slug__get: {
    parameters: {
      query?: {
        session_id?: string | null;
      };
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProblemDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_sessions_api_sessions_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Session"][];
        };
      };
    };
  };
  create_session_api_sessions_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SessionIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Session"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_session_api_sessions__session_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_session_api_sessions__session_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SessionPatch"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Session"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  session_stats_api_sessions__session_id__stats_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionStats"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  save_draft_api_sessions__session_id__problems__slug__draft_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
        slug: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CodeIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reset_draft_api_sessions__session_id__problems__slug__draft_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  run_api_sessions__session_id__problems__slug__run_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
        slug: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RunIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  submit_api_sessions__session_id__problems__slug__submit_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
        slug: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CodeIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SubmitResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_submissions_api_sessions__session_id__problems__slug__submissions_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path: {
        session_id: string;
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Submission"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_chat_api_sessions__session_id__problems__slug__chat_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatHistory"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  send_chat_api_sessions__session_id__problems__slug__chat_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
        slug: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChatIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatReply"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  clear_chat_api_sessions__session_id__problems__slug__chat_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_pattern_chat_api_sessions__session_id__patterns__slug__chat_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatHistory"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  send_pattern_chat_api_sessions__session_id__patterns__slug__chat_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
        slug: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChatIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatReply"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  clear_pattern_chat_api_sessions__session_id__patterns__slug__chat_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
